apiVersion: v1
kind: Service
metadata:
  name: php-blog
  labels:
    app: php-blog
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: php-blog
    